STD_STEERING_ANGLE_METRIC = "std_steering_angles"
STD_LATERAL_POSITION_METRIC = "std_lateral_positions"
STD_SPEED_METRIC = "std_speeds"
MAX_LATERAL_POSITION_METRIC = "max_lateral_positions"
QUALITY_METRICS_NAMES = [
    STD_STEERING_ANGLE_METRIC,
    STD_LATERAL_POSITION_METRIC,
    STD_SPEED_METRIC,
    MAX_LATERAL_POSITION_METRIC,
]

LATERAL_POSITION_FITNESS_NAME = "lateral_position_fitness"
CTE_FITNESS_NAME = "cte_fitness"
FITNESS_PAIR_NAME = "fitness_pair"
FITNESS_NAMES = [CTE_FITNESS_NAME, LATERAL_POSITION_FITNESS_NAME, FITNESS_PAIR_NAME]

STATE_INDIVIDUAL_NAME = "state_individual"
STATE_PAIR_INDIVIDUAL_NAME = "state_pair_individual"
INDIVIDUAL_NAMES = [STATE_INDIVIDUAL_NAME, STATE_PAIR_INDIVIDUAL_NAME]

REAL_EVALUATOR_NAME = "real"
MOCK_EVALUATOR_NAME = "mock"
EVALUATOR_NAMES = [MOCK_EVALUATOR_NAME, REAL_EVALUATOR_NAME]

RANDOM_SEED_STATE_GENERATOR_NAME = "random"
PERFORMANCE_SEED_STATE_GENERATOR_NAME = "performance"
SEED_STATE_GENERATOR_NAMES = [
    RANDOM_SEED_STATE_GENERATOR_NAME,
    PERFORMANCE_SEED_STATE_GENERATOR_NAME,
]

ONE_PLUS_LAMBDA_GENERATOR_NAME = "one_plus_lambda"
SEQUENCE_GENERATOR_NAME = "sequence"
INDIVIDUAL_GENERATOR_NAMES = [ONE_PLUS_LAMBDA_GENERATOR_NAME, SEQUENCE_GENERATOR_NAME]

ROAD_GENERATOR_TYPE = "road"
SEED_STATE_GENERATOR_TYPE = "state"
GENERATOR_TYPES = [ROAD_GENERATOR_TYPE, SEED_STATE_GENERATOR_TYPE]
